export const TENANT_ENTITY_MANAGER = 'TENANT_ENTITY_MANAGER';
export const TENANT_CONNECTION = 'TENANT_CONNECTION';
export const MONGO_ENTITY_MANAGER = 'MONGO_ENTITY_MANAGER';
export const MONGO_CONNECTION = 'MONGO_CONNECTION';
